### ISSUE TITLE
httpclient

### ISSUE THREAD

**Issue by pwin** [evolvedbinary/fusiondb-server#3]
I'm getting an error with 

`import module namespace httpclient="http://exist-db.org/xquery/httpclient"; `

Is this missing from the Alpha build?

**Comment by adamretter** [comment]
Hi @pwin eXist-db's legacy HTTP Client has been deprecated for some years now. It was removed from eXist-db 5, which we maintain compatibility with.

Instead it is recommended to migrate to the EXPath HTTP Client which has also been present in eXist-db for some years now.

Let me know if you need any further guidance on that...

**Comment by pwin** [comment]
Hi Adam
I'm clearly working with old codebases. A pointer to the best refactoring
approach would be helpful
Cheers
Peter

**Comment by adamretter** [comment]
@pwin Sure. If I recall correctly you are migrating from eXist-db 2.2?

FusionDB Alpha 1 is backwards compatible with eXist-db 5.0.0-RC8.

The release notes for eXist-db 5.0.0-RC8, in particular the `Removed` section, will be useful for you - http://www.exist-db.org/exist/apps/wiki/blogs/eXist/eXistdb500RC8 . From there you will also find a link to a Perl script from Craig Berry, which you can run against XQuery code to identify migration issues.

**Comment by pwin** [comment]
That's really helpful. Thanks
